# Generated by Django 4.2.5 on 2023-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
